//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSFTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YSFTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal et.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string buttonClose {
            get {
                return ResourceManager.GetString("buttonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni dosya oluştur.
        /// </summary>
        public static string buttonCreateFile {
            get {
                return ResourceManager.GetString("buttonCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasör oluştur.
        /// </summary>
        public static string buttonCreateFolder {
            get {
                return ResourceManager.GetString("buttonCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndir.
        /// </summary>
        public static string buttonDownload {
            get {
                return ResourceManager.GetString("buttonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMM.
        /// </summary>
        public static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        public static string buttonRefresh {
            get {
                return ResourceManager.GetString("buttonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeniden adlandır.
        /// </summary>
        public static string buttonRename {
            get {
                return ResourceManager.GetString("buttonRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string buttonUpdate {
            get {
                return ResourceManager.GetString("buttonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya adı.
        /// </summary>
        public static string gridViewColumnFilename {
            get {
                return ResourceManager.GetString("gridViewColumnFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya boyutu.
        /// </summary>
        public static string gridViewColumnFilesize {
            get {
                return ResourceManager.GetString("gridViewColumnFilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya türü.
        /// </summary>
        public static string gridViewColumnFiletype {
            get {
                return ResourceManager.GetString("gridViewColumnFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son değişiklik.
        /// </summary>
        public static string gridViewColumnLastmodified {
            get {
                return ResourceManager.GetString("gridViewColumnLastmodified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sahip/Grup.
        /// </summary>
        public static string gridViewColumnOwnerGroup {
            get {
                return ResourceManager.GetString("gridViewColumnOwnerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki.
        /// </summary>
        public static string gridViewColumnPermissions {
            get {
                return ResourceManager.GetString("gridViewColumnPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        public static string groupBoxServerOptions {
            get {
                return ResourceManager.GetString("groupBoxServerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı sunucular.
        /// </summary>
        public static string groupBoxServers {
            get {
                return ResourceManager.GetString("groupBoxServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlar.
        /// </summary>
        public static string tabItemLog {
            get {
                return ResourceManager.GetString("tabItemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuyruk.
        /// </summary>
        public static string tabItemQueue {
            get {
                return ResourceManager.GetString("tabItemQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres:.
        /// </summary>
        public static string textBlockAddress {
            get {
                return ResourceManager.GetString("textBlockAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretici.
        /// </summary>
        public static string textBlockCompanyName {
            get {
                return ResourceManager.GetString("textBlockCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telif hakkı.
        /// </summary>
        public static string textBlockCopyright {
            get {
                return ResourceManager.GetString("textBlockCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string textBlockDescription {
            get {
                return ResourceManager.GetString("textBlockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string textBlockPort {
            get {
                return ResourceManager.GetString("textBlockPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün adı.
        /// </summary>
        public static string textBlockProductName {
            get {
                return ResourceManager.GetString("textBlockProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunucu adı.
        /// </summary>
        public static string textBlockServerName {
            get {
                return ResourceManager.GetString("textBlockServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı:.
        /// </summary>
        public static string textBlockUserName {
            get {
                return ResourceManager.GetString("textBlockUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola:.
        /// </summary>
        public static string textBlockUserPass {
            get {
                return ResourceManager.GetString("textBlockUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sürüm.
        /// </summary>
        public static string textBlockVersion {
            get {
                return ResourceManager.GetString("textBlockVersion", resourceCulture);
            }
        }
    }
}
